### ISSUE TITLE
Setting algorithm to md5 for new project triggers immediate scan

### ISSUE THREAD

**Issue by andrewjbtw** [avpreserve/fixity#10]
When changing the default checksum algorithm for a new project, you need to do the following steps:

1. Save the project.
2. Change the algorithm using the Checksum Manager dialogue.

Making this change triggers an immediate scan. I would like to be able to set the initial scan to be scheduled, as can be done with the default settings.

**Comment by clacinak** [comment]
Fixed in release of 0.5
