### ISSUE TITLE
SMTP Preference Test Failure

### ISSUE THREAD

**Issue by cshieber** [avpreserve/fixity#11]
Hi,

Whenever check credentials in email settings, I receive the following error:

Fixity was unable to send emails from the provided account. 
*Please ensure that you are connected to the internet
*Please ensure that your email credentials are correct

We do not use direct internet connection for email, but rather an interal SMTP gateway.  Our Corporate SMTP gateway permits anonymous logons, however I can't setup the email settings within Fixity without inputting a password.

Is there a way of putting in a blank password into the email settings?

Thanks

Colin

**Comment by clacinak** [comment]
Will look into this and see what we can do.

**Comment by clacinak** [comment]
Fixed in the the release of 0.5
