### ISSUE TITLE
Subfolders without acces rights are beeing ignored

### ISSUE THREAD

**Issue by DCEM** [avpreserve/fixity#13]
When there is a Subfolder that fixity is not allowed to read it will do so without any notification or error.

**Comment by clacinak** [comment]
What would you like/expect to happen in this instance?

**Comment by DCEM** [comment]
I would like to have some sort of error/notification in the report...
The same should be happening if a file/folder cannot be read for any other reason (locked/opened) etc.

At the moment you might screw up your rights management for a subfolder and you think nothing is changing there because fixity just ignores that folder (because it cannot read it) 
If you are doing "File Fixity" as in digital preservation i think you want to know when you cannot read something for whatever reason ...

**Comment by DCEM** [comment]
I hope the comment above does not sound harsh or rude, i'm not a native english writer and hope you excuse errors or poor choice of words.

I ment do do some constructive criticism and I appreciate that you are developing this as open source.

Greetings,
David

**Comment by clacinak** [comment]
David, not at all! You're great. We very much appreciate the feedback! Keep it coming.

-Chris

**Comment by clacinak** [comment]
This has been added to the backlog of issues in addition to a notification process and improved behavior when access to a drive is disabled during a scheduled Fixity scan.
