### ISSUE TITLE
False changed files

### ISSUE THREAD

**Issue by lowa80** [avpreserve/fixity#14]
The reports generated indicate that only one file in the folder is confirmed and that the same file has changed to the other files in the folder. For example:

Changed File:	H:\BornDigital\ReadingNotes\Email\PreservingEmail.docx	 changed to	H:\BornDigital\ReadingNotes\Email\Capstone.docx

Changed File:	H:\BornDigital\ReadingNotes\Email\PreservingEmail.docx	 changed to	H:\BornDigital\ReadingNotes\Email\PolicyDesignEMess.docx

Confirmed File:	H:\BornDigital\ReadingNotes\Email\PreservingEmail.docx

**Comment by clacinak** [comment]
Thanks for the note. Is the example you are giving the actual example/filepaths encountered? Are these .docx files or another type of file? Are you on Windows or Mac OS? Can you send me the files at chris@avpreserve.com?
