### ISSUE TITLE
Not running at night - Notepad window opens

### ISSUE THREAD

**Issue by edbusch** [avpreserve/fixity#17]
I've got Fixity set to run during the night. When I come in the next day, I find a Notepad window open with
Dim location, p
location = WScript.ScriptFullName
p = Replace(location, "fixity-Images_HCs.vbs", "fixity-Images_HCs.bat")
Set WinScriptHost = CreateObject("WScript.Shell")
WinScriptHost.Run("""" & p & """")
Set WinScriptHost = Nothing

and it has not executed. I can run checks manually fine. I'm on a PC with Windows 7. This happens for all of my projects.

**Comment by Fuqran** [comment]
Hi edbusch, 
       This is developer of Fixity. From the look of this error.It seems like VB( Visual Basic) is not properly working on your system. Just to make sure your VB( Visual Basic) is working.

Please follow steps below 

1. Create a File in a separate folder with the extension of **.vbs* (for example test.vbs)
2. After that, open this file in any text editor and paste the code into it     *MsgBox "Well come to Fixity!"*   
3. Save it and double click it 
4. if a popup appears on the screen saying  "Well come to Fixity!".Which means VB is working and If this file also opens in a notepad or another program then it mean there is something wrong with VB on your system. either in installation or configuration. 
5. More Over go into ->*Fixity* folder then go into -> *schedules* folder. From there right click on file with extension *.vbs*. Which will open its properties. From properties click on a button named "Change". Then change the default program to *Microsoft Windows Based Script Host*, just make sure default program to run VB script is correct.After that try test.vbs file again  and also Fixity and see if that works.If  *Microsoft Windows Based Script Host* is not listed in properties programs selection. which means VB is not installed (refer to point 7 )
6. If Vb dose not work, Also try Fixity on fresh user and see if that works.

7. If nothing above fixes the problem 
Refer to urls below for VBS installation/Re-Installation/Configuraiton
https://sahil.xyz/install-visual-basic-6-vb6-on-windows-7-windows-8/
http://techapple.net/2013/10/installing-and-running-microsoft-visual-basic-6-0-on-windows-7windows-8-x64-64-bit-with-all-features/

**Comment by edbusch** [comment]
Yep, I think it was the properties. I'll schedule a run for tonight. Thanks!

**Comment by Fuqran** [comment]
sounds good!
