### ISSUE TITLE
Unable to schedule the fixity check

### ISSUE THREAD

**Issue by som2** [avpreserve/fixity#18]
Hello,

I tried to schedule an automatic fixity check for my files.  I read all your documentation and followed all the steps that you mentioned.  However, I am having problem setting up an automatic fixity checks for my files and folders.

Thanks

**Comment by clacinak** [comment]
Hello,

I have a few questions for you.

1- Which OS are you using?

2- If Windows, which one? Also, do you know how to review Windows Scheduler? This is a place you should check to see if the task is being scheduled and what the status of the task is.

3. If using MAC then go to this path ~/Library/LaunchAgents/ (cd ~/Library/LaunchAgents/) and see if there is a file along the lines of “Com.fixity.GivenName.demon.plist”. If this exists it means the task is created and scheduled.

4- Can you turn debugging on and run the tasks through the point of failure. You do this by turning "debugging" on within the preferences. After you run Fixity through the point of failure you can close Fixity and navigate to the directory within the Fixity parent directory called "debug". Inside of that directory you should find the log file to send to us.

Thanks

**Comment by som2** [comment]
Thank you for your response.

Below are the answers to your questions.

1.  I am using Windows 8.1
2. I reviewed the windows scheduler.  The status shows "running".

I have sent you windows scheduler screenshot in this email.  Do I need to email the log file as well?

Thanks.






--------------------------------------------
On Tue, 8/23/16, clacinak <notifications@github.com> wrote:

 Subject: Re: [avpreserve/fixity] Unable to schedule the fixity check (#18)
 To: "avpreserve/fixity" <fixity@noreply.github.com>
 Cc: "som2" <samridhiojha@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Tuesday, August 23, 2016, 9:35 AM
 
 Hello,
 
 I have a few questions for you.
 
 1- Which OS are you using?
 
 2- If Windows, which one? Also, do you know how to review
 Windows Scheduler? This is a place you should check to see
 if the task is being scheduled and what the status of the
 task is.
 
 
 If using MAC then go to this path
 ~/Library/LaunchAgents/ (cd ~/Library/LaunchAgents/) and see
 if there is a file along the lines of
 “Com.fixity.GivenName.demon.plist”. If this exists it
 means the task is created and scheduled.
 
 
 4- Can you turn debugging on and run the tasks through
 the point of failure. You do this by turning
 "debugging" on within the preferences. After you
 run Fixity through the point of failure you can close Fixity
 and navigate to the directory within the Fixity parent
 directory called "debug". Inside of that directory
 you should find the log file to send to us.
 
 Thanks
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by atmickle** [comment]
Hello, 

I had a similar problem using Windows 10, after moving from Windows 7. The status of the scheduler job was running, but it never finished. I was able to edit the Scheduled Task to work by changing the Action to run Wscript.exe with the fixity script as the Argument, but this means it can't be edited in the Fixity interface by the Archivist. 

Thank you, 
Audrey

**Comment by rickgrimm** [comment]
Cheers to @atmickle 🎆 🍾 😀 !!!! 

That finally got Fixity working for us on a scheduled task running Server 2016, we had the same issue on Server 2012 R2..

Thanks!
Rick

**Comment by clacinak** [comment]
Thanks for the info. We will look into this on our side to see if there is anything we can do to mitigate the issue.

Thanks!

Chris

**Comment by clacinak** [comment]
The latest windows download has addressed this issue.
