### ISSUE TITLE
Excessive writes to Fixity.db during verify, potential wear problem for flash/solid state drive?

### ISSUE THREAD

**Issue by Mountain-Eagle** [avpreserve/fixity#19]
I have been testing Fixity for my small business records archive and it is working OK.
I do not use hard disk drives any more. All my drives are SSD and flash drives.  Flash memory has a limited life due to wear during write cycles. SSDs include wear leveling to replace worn blocks, but flash drives do not.  Reading does not cause a problem.

I noticed that when Fixity is running a verification, it is constantly writing/updating the Fixity.db file.  I ran a verify on one of my archives on an SSD and it took about 30 minutes, and appeared to be constantly writing the .db file.

My question/concern: does Fixity do many writes to the drive during the verify? 
If so, is this a potential wear problem when using an SSD or flash drive?
If it is wearing out my flash drive, then I will run the file verification less often.

**Comment by clacinak** [comment]
Hello, Fixity does update the db when it performs a verification, but I wouldn't categorize it as excessive in any way.
