### ISSUE TITLE
Linux/Ubuntu binaries?

### ISSUE THREAD

**Issue by kieranjol** [avpreserve/fixity#22]
Hi,

I'm just wondering if there are any Ubuntu binaries, or instructions for how to install on Linux?

**Comment by clacinak** [comment]
Hello Kieran,

I'm sorry to say that we do not have either of those.

-Chris

**Comment by kongbb1** [comment]
Hello,
Is is easy to move the project from Windows/Mac os version to Linux version?
And do you have some suggesstion if we transfer this project to linux version?
thans!

**Comment by clacinak** [comment]
@kongbb1 I'm sorry that we don't have suggestions for this since it is not something we've done or supported.
